name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ayaka14732 --password-stdin
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/ayaka14732/graphviz-server:${{ github.sha }}
    - name: Push to GitHub Packages
      run: docker push ghcr.io/ayaka14732/graphviz-server:${{ github.sha }}
